title:              Haley Nakamura | Portfolio |
email:              halnak@mit.edu
description:        I'm a computer science and engineering student at MIT. Here are a few of my favorite projects!
author:             Haley Nakamura
baseurl:            "/"
url:                "https://halnak.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    halnak
# facebook_username:  StartBootstrap
# instagram_username:  
linkedin_username:   haley-nakamura

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
